### ISSUE TITLE
Create workflow to build and deploy website using hugo

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#4]
Add a workflow to build the static site using hugo and then upload to the web server using scp. 

Hugo binary can be installed from here:

https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_0.122.0_Linux-64bit.tar.gz

Requires the following setup for access:

- [x] Account on the server with proper directory permissions
- [x] Public key added to `~/ssh/authorized_keys`
- [x] Private key added to repository secrets
- [x] Need to know target directory on the server

(above setup items for @molinaro-m to complete)

**Comment by molinaro-m** [comment]
Some steps done.
The target directory is `ivoa-web-stage` reachable via cd from an sftp call through `sftp webstage@web.ivoa.net`.

Keys for _webstage_ user have been created.

About the one to be added to repo secrets: should it go into __deploy keys__ or under __secrets and variables__ possibly __codespaces__ section?

**Comment by molinaro-m** [comment]
`STAGE_ID` added to repository secrets, useful for `webstage` user on ivoa.info.
Remember to `cd` into `ivoa-web-stage` once opened sftp connection.

If all works, I suppose a test is needed, this issue can be closed.

**Comment by JeremyMcCormick** [comment]
Thank you for setting everything up, @molinaro-m

I plan to use this gh action:

https://github.com/marketplace/actions/sftp-upload

**Comment by JeremyMcCormick** [comment]
This was resolved in #7
