### ISSUE TITLE
Add newsletters page

### ISSUE THREAD

**Issue by gmantele** [ivoa/ivoa-web#40]
The [newsletters](https://ivoa.net/newsletter/index.html) will have to be added in the `static/newsletter/` directory.

The newsletter of March already in this repo is incomplete.

**Comment by JeremyMcCormick** [comment]
Should we instead create an archive with the HTML newsletters?

I am not sure that converting all the newsletters to markdown is worth the time and effort, and getting all the formatting right could be tricky.

**Comment by JeremyMcCormick** [comment]
@gmantele After discussing with @molinaro-m, we decided the best approach here is just converting all of these to PDF (via _Chrome -> Print to PDF_ should be fine) and linking to them as static assets under `static/newsletters`. We felt that It is not worth the time or effort to convert them to markdown.

How the newsletters will be authored in the future is still an open question, to my understanding. It may be done in markdown, in which case we can have different linking for the new ones. I think we should basically mark all the old ones as an "archive" and treat them differently.
