### ISSUE TITLE
Code of conduct should have a page rather than a PDF

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#53]
It would be better to have a dedicated page for the code of conduct rather than a PDF.

**Comment by gmantele** [comment]
That should probably decided by TCG/Exec as it came originally from them. There maybe be a reason to have it as a PDF instead of an HTML page (e.g. easy to download, 1 version = 1 file with an explicit date while a date in an HTML page might not be up-to-date, ....). If no reason at all, why not having it as a page on the website.

**Comment by Zarquan** [comment]
We made a start on putting the IVOA code of conduct in version control, but it hasn't been approved by the exec yet.
https://github.com/ivoa/CodeOfConduct/

It contains an mark down version here:
https://github.com/ivoa/CodeOfConduct/blob/main/CODE_OF_CONDUCT.md

**Comment by JeremyMcCormick** [comment]
I don't have any strong preference, and we can of course keep it as a PDF. Just from using sites of other organizations, it would be fairly typical to have this as part of the site content and not an external document. The PDF contents could just be used exactly. (It just seems clunky to me that it is not actually content on the site and has to be viewed as a PDF, especially when it is just a one page document.)

**Comment by molinaro-m** [comment]
The reason for PDF I think is to have an "fixed" CoC while the other solutions are easily modifiable, version control or not in place.
To me the solution would be a markdown one (maybe coming from Dave's repo, if Exec complies) with a visible link to the Exec approved PDF.
It's more things to maintain, but in the end it only requires checking `coc.md.isequal(coc.pdf.innertext) = T`.
