### ISSUE TITLE
Improve Look and Feel

### ISSUE THREAD

**Issue by KlaasYK** [ivoa/ivoa-web#6]
After consulting the UI/UX designed in our team he came up with the following points:

* Prefer a darker theme (which seems more common on astronomical websites)
* Remove the underline on links (which makes it look very dated)
* Change the font to use something like `Inter`: https://fonts.google.com/specimen/Inter (but any modern font would do)
* Add some more colour, for example under the Category titles
* The IVOA logo seems to complex (lot's of detail)

He also made a quick mock-up in his design tool (ignore the login part):

![Prototype](https://github.com/ivoa/ivoa-web/assets/8835517/fb89aa8c-7c40-41c7-b84b-c226f412c42c)

**Comment by msdemlei** [comment]
On Fri, Feb 09, 2024 at 03:17:21AM -0800, Klaas Kliffen wrote:
> * Remove the underline on links (which makes it look very dated)

Frankly, I feel weighing "follow fashion" versus "make sense" (clearly
marking where you can click) should always prefer "makes sense".

So, my vote is to have underlined links (outside of menus and
similar, where clickability is implied).

**Comment by gmantele** [comment]
I personally really like it :1st_place_medal: . I prefer this version compared to the current prototype.
Maybe the logo + title "IVOA" are a bit too dark compared to the background, and so, not enough contrasted (might be an issue to visually impaired persons).

**Comment by JeremyMcCormick** [comment]
How do we precede from this mock-up to to layout/stylesheets/etc. ?

I personally like it as an initial design to start.

**Comment by JeremyMcCormick** [comment]
> On Fri, Feb 09, 2024 at 03:17:21AM -0800, Klaas Kliffen wrote: * Remove the underline on links (which makes it look very dated)
> Frankly, I feel weighing "follow fashion" versus "make sense" (clearly marking where you can click) should always prefer "makes sense". So, my vote is to have underlined links (outside of menus and similar, where clickability is implied).

I don't think we should get caught up on this one way or another. It should be just a single change to the stylesheet to add or remove the underlining. I personally like no underlining but I'm fine either way. (Probably something for a broader discussion group even if it seems like a minor design issue.)

**Comment by JeremyMcCormick** [comment]
I would change "Deployers/Developers" -> "For Developers"

"Deployers" seems like awkward language. :)

"Members section" -> "For Members"

**Comment by JeremyMcCormick** [comment]
> The IVOA logo seems to complex (lot's of detail)

I actually like the [current logo](https://www.ivoa.net/images/ivoa_logoc2.jpg) and don't think it is too complicated.

Though I do wonder if the color scheme will look good on a dark background. The outline is black, for instance, and this will be obscured.

**Comment by JeremyMcCormick** [comment]
Would the page links on the bottom be more visible if the text was white?

The NASA site has a dark background with white text. Light blue on dark blue is a little bit hard to read.
