### ISSUE TITLE
Normalize file naming conventions of directories and markdown files

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#66]
Decide whether to use underscores or dashes in file names.

I suggest to use dashes rather than underscores as this is the more common convention.

It would also be appropriate to simply remove spaces entirely, and use instead file names like `gettingstarted`, instead of `getting_started`, etc.

**Comment by molinaro-m** [comment]
I haven't a strong opinion on what solution to choose.
My only comment stays: this will break links here and there (e.g. wiki).
I consider that a minor thing that will solve itself over time.

**Comment by JeremyMcCormick** [comment]
> I haven't a strong opinion on what solution to choose.
> 
> My only comment stays: this will break links here and there (e.g. wiki).
> 
> I consider that a minor thing that will solve itself over time.

With a site redesign, it would be expected that many links to subpages will be broken, but I don't think that is a reason not to proceed and make the paths and file names more consistent.

**Comment by gmantele** [comment]
A common practice in Hugo to build automatically anchors is to replace spaces (and non alpha numerical characters) with a dash. This would make `getting-started`.

Then, to be consistent with the choice of Hugo, I would prefer the solution to not get rid of spaces but replace them with dashes. Besides, I find it more readable by human eyes (you still see a separation between words ; so, you see more clearly words which makes it more readable).

**Comment by JeremyMcCormick** [comment]
> A common practice in Hugo to build automatically anchors is to replace spaces (and non alpha numerical characters) with a dash. This would make `getting-started`.
> 
> 
> 
> Then, to be consistent with the choice of Hugo, I would prefer the solution to not get rid of spaces but replace them with dashes. Besides, I find it more readable by human eyes (you still see a separation between words ; so, you see more clearly words which makes it more readable).

I am fine with using dashes for readibility instead of getting rid of spaces between words entirely.

**Comment by JeremyMcCormick** [comment]
This will be resolved on #78.
