### ISSUE TITLE
Remove home link from top menu

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#67]
It isn't necessary, since the IVOA logo links back to the homepage.

**Comment by molinaro-m** [comment]
The answer here relies in UX/UI, I think different people will have different opinions.
Is it really bad to have the extra link to home at the top?

**Comment by JeremyMcCormick** [comment]
> The answer here relies in UX/UI, I think different people will have different opinions.
> 
> Is it really bad to have the extra link to home at the top?

These links will be turned into a dropdown menu, I believe. The link can be kept and would appear as the top item in the menu.

**Comment by molinaro-m** [comment]
That, to me, speaks for keeping it. Despite the duplication "home" is a clear concept and a logo might not convey it (it's convention).
