### ISSUE TITLE
Incorporate content of `docs/README.md` into the contributing guide

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#68]
Move content into the contributing guide from `docs/README.md` that is not already present and then delete this file and directory. (I don't think we need a `docs` directory at all right now.)

**Comment by gmantele** [comment]
Having a `README.md` is a very common best practice even if it does not contain anything. After all, this is the first thing displayed by GitHub on the landing page of a GitHub repository.It does not have to be long. It can just say, what this repository is for and encourage collaborators to read the contributing guide. Eventually, it can say what technologies are used: Hugo, Markdown. It could also say that CI workflow is set up to display a preview for each branch and to deploy the main branch on the public website ; then, it would be the good moment to give the link of the public website and how to access the listing page of all branches preview.

**Comment by JeremyMcCormick** [comment]
> Having a `README.md` is a very common best practice even if it does not contain a lot of thing. After all, this is the first thing displayed by GitHub on the landing page of a GitHub repository.It does not have to be long. It can just say, what this repository is for and encourage collaborators to read the contributing guide. Eventually, it can say what technologies are used: Hugo, Markdown. It could also say that CI workflow is set up to display a preview for each branch and to deploy the main branch on the public website ; then, it would be the good moment to give the link of the public website and how to access the listing page of all branches preview.

We have the README in the root directory - the one in docs has information on contributing so we should move that over to `CONTRIBUTING.md`.

**Comment by gmantele** [comment]
Ho, sorry, I thought you were speaking about the root `README.md` file. I guess I was too hasty when reading this issue.

In this case, yes, I agree with your proposition :+1:
