### ISSUE TITLE
Delete unnecessary files and directories

### ISSUE THREAD

**Issue by JeremyMcCormick** [ivoa/ivoa-web#69]
I believe all of these could be deleted:

`Dockerfile`

`assets/`

`data/`

`resources/`

**Comment by gmantele** [comment]
I agree to remove:
- `Dockerfile`
- `resources/`

But please, do not remove yet the following:
- `assets/` (I will use it when cleaning up the CSS stylesheet of the website)
- `data/` (it may be useful for some special pages like the VO glossary, members, ...)
